FROM node:20-alpine as build 

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./   
COPY src ./src
COPY alias ./alias

RUN npm install
RUN npm run build

FROM node:20-alpine as production

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/alias ./alias
COPY --from=build /app/package*.json ./
COPY --from=build /app/node_modules ./node_modules


EXPOSE 3000