name: production deployment

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: true
        registry-type: private
        skip-logout: false

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.PROD_ECR_REGISTRY }}:${{ github.sha }} .

    - name: Tag Docker image
      run: |
        docker tag ${{ secrets.PROD_ECR_REGISTRY }}:${{ github.sha }} ${{ secrets.PROD_ECR_REGISTRY }}:latest

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.PROD_ECR_REGISTRY }}:${{ github.sha }}
        docker push ${{ secrets.PROD_ECR_REGISTRY }}:latest